DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE  MEMBER
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    NICKNAME VARCHAR NOT NULL UNIQUE,
    LOGIN_ID VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    REGISTER_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR NOT NULL
);